# Basic CI pipeline to deploy "ni-microservice-nodejs" as an AWS Lambda function.
# This files assume you are running CI for develop (dev) and master (prod) branches only.
# In a bigger project you way have more deployments, so you'll need to customise the setup a little bit.
# Note: Do remember to protect your develop and master branches and be sure your CI variables are hidden in the setup on GitLab side.
# GitHub Repository: https://github.com/numerica-ideas/ni-microservice-nodejs
#
# @author dassiorleando
image: node:latest

# Some CI stages to run in order, one after another.
# Let's build the micro-service, then test it prior to deployment.
stages:
  - build
#  - test (enable this to run some automated tests before deployments, recommended).
  - deploy

# Let's save time by caching the 'node_modules' amongst stages/pipelines
# Since most of the times the package.json is the same.
cache:
  paths:
    - node_modules/

# The dependencies job (build stage), that run `npm install` to make sure we have all our dependencies in place
dependencies:
  stage: build
  script: npm install
  artifacts:
    paths:
      - node_modules/
  only:                   # We run the build stage for develop and master branches only.
  - master
  - develop

# To be enabled if the tests are performed prior to deployment (recommended)
# testing:
#   stage: test
#   script: npm test
#   only:
#   - master
#   - develop

# Development deployment job, part of the `deploy` stage but for develop branch only.
dev_deployment:
  stage: deploy
  only:
  - develop
  script:
  - apt-get update -y                       # Updating the Ubuntu Docker instance.
  - python -V                               # Print out python version (for debugging only).
  - apt install -y python-pip               # Install pip.
  - pip install awscli --upgrade --user     # Install aws cli utility.
  - export PATH=~/.local/bin:$PATH          # Required for awscli, the PATH.
  - aws --version                           # Print out aws cli version (for debugging only).
  - npm run deploy:dev                      # Run the dev deployment script.

# Production deployment job, part of the `deploy` stage but for master branch only.
prod_deployment:
  stage: deploy
  only:
  - master
  script:
  - apt-get update -y                       # Updating the Ubuntu Docker instance.
  - python -V                               # Print out python version (for debugging only).
  - apt install -y python-pip               # Install pip.
  - pip install awscli --upgrade --user     # Install aws cli utility.
  - export PATH=~/.local/bin:$PATH          # Required for awscli, the PATH.
  - aws --version                           # Print out aws cli version (for debugging only).
  - npm run deploy:prod                     # Run the prod deployment script.
