# Basic CI pipeline to deploy "ni-microservice-nodejs" as an AWS Lambda function.
# This files assume you are running CI for develop (dev) and master (prod) branches only.
# In a bigger project you way have more deployments, so you'll need to customise the setup a little bit.
# Note: Do remember to protect your develop and master branches and be sure your CI variables are hidden in the setup on GitLab side.
# GitHub Repository: https://github.com/numerica-ideas/ni-microservice-nodejs
#
# @author dassiorleando
image: node:latest

# Some CI stages to run in order, one after another.
# Let's build the micro-service, then test it prior to deployment.
stages:
  - build
  - test
  - deploy

# Let's save time by caching the 'node_modules' amongst stages/pipelines
# Since most of the times the package.json is the same.
cache:
  paths:
    - node_modules/

# The build stage: install dependencies then compile TypeScript files to JS ones
dependencies:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules/
  only:                   # We run the build stage for develop and master branches only.
  - master
  - develop

# Run tests as part of the pipelines (test stage)
testing:
  stage: test
  script: npm test
  only:
  - master
  - develop

# Development deployment job, part of the `deploy` stage but for develop branch only.
dev_deployment:
  stage: deploy
  only:
  - develop
  script:
  - apt-get update -y                       # Updating the linux distribution.
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip -u awscliv2.zip
  - ./aws/install                           # Install aws-cli v2 from the downloaded zip file.
  - rm -rf awscliv2.zip
  - aws --version                           # Print aws-cli version (for debug only).
  - npm run deploy:dev                      # Run the dev deployment script.

# Production deployment job, part of the `deploy` stage but for master branch only.
prod_deployment:
  stage: deploy
  only:
  - master
  script:
  - apt-get update -y                       # Updating the linux distribution.
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip -u awscliv2.zip
  - ./aws/install                           # Install aws-cli v2 from the downloaded zip file.
  - rm -rf awscliv2.zip
  - aws --version                           # Print aws-cli version (for debug only).
  - npm run deploy:prod                     # Run the prod deployment script.
